config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get'home', to: 'pages#home'

  get'activities', to: 'pages#activities'
  get'animals', to: 'pages#animals'
  get'clothes', to: 'pages#clothes'
  get 'body', to: 'pages#body'
  get'colors', to: 'pages#colors'
  get'dashboard', to: 'pages#dashboard'
  get'family', to: 'pages#family'
  get'food', to: 'pages#food'
  get'fruits', to: 'pages#fruits'
  get'house', to: 'pages#house'
  get'letters', to: 'pages#letters'
  get'music', to: 'pages#music'
  get'nature', to: 'pages#nature'
  get'numbers', to: 'pages#numbers'
  get'school', to: 'pages#school'
  get 'shapes', to: 'pages#shapes'
  get'sports', to: 'pages#sports'
  get'vegetables', to: 'pages#vegetables'
  get'vehicules', to: 'pages#vehicules'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= favicon_link_tag %>
    <title>KidEnglish</title>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/animals.html.erb
<%= link_to 'back', dashboard_path %>

<div class="animals">

  <div class="mini">
    <h3>Chat</h3>
    <%= image_tag'' %>
    <h3>Cat</h3>
  </div>
  <div class="mini">
    <h3>Chien</h3>
    <%= image_tag'' %>
    <h3>Dog</h3>
  </div>
  <div class="mini">
    <h3>Poisson</h3>
    <%= image_tag'' %>
    <h3>Fish</h3>
  </div>
  <div class="mini">
    <h3>Souris</h3>
    <%= image_tag'' %>
    <h3>Mouse / Mice</h3>
  </div>
  <div class="mini">
    <h3>Ours</h3>
    <%= image_tag'' %>
    <h3>Bear</h3>
  </div>
  <div class="mini">
    <h3>Cheval</h3>
    <%= image_tag'' %>
    <h3>Horse</h3>
  </div>
  <div class="mini">
    <h3>Vache</h3>
    <%= image_tag'' %>
    <h3>Cow</h3>
  </div>
  <div class="mini">
    <h3>Cochon</h3>
    <%= image_tag'' %>
    <h3>Pig</h3>
  </div>
  <div class="mini">
    <h3>Mouton</h3>
    <%= image_tag'' %>
    <h3>Sheep</h3>
  </div>
  <div class="mini">
    <h3>Elephant</h3>
    <%= image_tag'' %>
    <h3>elephant</h3>
  </div>
  <div class="mini">
    <h3>Lion</h3>
    <%= image_tag'' %>
    <h3>Lion</h3>
  </div>
  <div class="mini">
    <h3>Ecureuil</h3>
    <%= image_tag'' %>
    <h3>Squirel</h3>
  </div>



</div>

app/views/pages/clothes.html.erb
<%= link_to 'back', dashboard_path %>

app/views/pages/dashboard.html.erb
<div class="dashboard">

  <div class="up">
    <div class="nav">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/dhxefoe7j/image/upload/v1668800961/Kidenglish/kigEnglish_Logo_kp0bx7.png", width:40 %>
      <% end %>
    </div>

    <div class="what">
      <h1>C'est parti !          What do you want to learn ?</h1>
    </div>
  </div>

  <div class="dashbox">

    <div class="banner">
      <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1668804765/Kidenglish/kidbanner_cut_yj13hk.png', width:'100%' %>
    </div>

    <div class="dashgrid">

    <div class="card">
        <%= link_to "Chiffres", numbers_path %>
      </div>

    <div class="card">
      <%= link_to "Lettres", letters_path %>
    </div>

     <div class="card">
      <%= link_to "Couleurs", colors_path %>
    </div>

     <div class="card">
      <%= link_to "Formes", shapes_path %>
    </div>

    </div>
  </div>



</div>

app/views/pages/family.html.erb
<%= link_to 'back', dashboard_path %>

app/views/pages/fruits.html.erb
<%= link_to 'back', dashboard_path %>

app/views/pages/home.html.erb
<br><br>
<div class="homeee">

  <%# <div class="kidy">
    <h1> Welcome to <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1668870890/Kidenglish/kigEnglish_Logo_1_gavxzw_rasw3y.png', width:'30%' %>
  <%# </div> %>

  <div class="landing">
    <%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1668871174/Kidenglish/Lets_learn_together_1_sswqbn.png', width:'100%' %>
    <div class="linkk">
      <%= link_to "Let's go ! ", dashboard_path, class:"middle" %>
    </div>
  </div>



</div>

app/views/pages/house.html.erb
<%= link_to 'back', dashboard_path %>

app/views/pages/letters.html.erb
<br><br>
<%= link_to 'Retour', dashboard_path, class:"back" %>
<br><br>
<div class="letters">

  <div class="mini">
    <h3> <%= link_to "A","#" %> </h3>
  </div>
  <div class="mini">
    <h3> <%= link_to"B", "#" %> </h3>
  </div>
  <div class="mini">
    <h3><%= link_to"C", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"D", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"E", "#" %></h3>
  </div>

  <div class="mini">
    <h3><%= link_to"F", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"G", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"H", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"I", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"J", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"K", "#" %></h3>
  </div><div class="mini">
    <h3><%= link_to"L", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"M", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"N", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"O", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"P", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"Q", "#" %></h3>
  </div>

  <div class="mini">
    <h3><%= link_to"R", "#" %></h3>
  </div><div class="mini">
    <h3><%= link_to"S", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"T", "#" %></h3>
  </div>

  <div class="mini">
    <h3><%= link_to"U", "#" %></h3>
  </div><div class="mini">
    <h3><%= link_to"V", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"W", "#" %></h3>
  </div>
  <div class="mini">
    <h3><%= link_to"X", "#" %></h3>
  </div>

  <div class="mini">
    <h3><%= link_to"Y", "#" %></h3>
  </div><div class="mini">
    <h3><%= link_to"Z", "#" %></h3>
  </div>




</div>

app/views/pages/music.html.erb
<%= link_to 'back', dashboard_path %>

app/views/pages/nature.html.erb
<%= link_to 'back', dashboard_path %>

app/views/pages/numbers.html.erb
<br><br><%= link_to 'Retour', dashboard_path, class:"back" %>
<br><br>
<div class="numbers">

  <div class="mini">
    <h3>Un</h3>
    <h3>One</h3>
    <%= image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1668855070/Kidenglish/Sans_titre_-_2022-11-19T114927.514_mpec42.png", width:120 %>
  </div>
  <div class="mini">
    <h3>Deux</h3>
    <h3>Two</h3>
    <%= image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1668855070/Kidenglish/Sans_titre_-_2022-11-19T114801.569_hbhjwq.png", width:120 %>
  </div>
  <div class="mini">
    <h3>Trois</h3>
    <h3>Three</h3>
    <%= image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1668855070/Kidenglish/Sans_titre_-_2022-11-19T114853.797_riyxj4.png", width:120 %>
  </div>
  <div class="mini">
    <h3>Quatre</h3>
    <h3>Four</h3>
    <%= image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1668855071/Kidenglish/Sans_titre_-_2022-11-19T114831.742_jshmxv.png", width:120 %>
  </div>
  <div class="mini">
    <h3>Cinq</h3>
    <h3>Five</h3>
    <%= image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1668855070/Kidenglish/Sans_titre_-_2022-11-19T115047.576_lvnhe7.png", width:120 %>
  </div>
  <div class="mini">
    <h3>Six</h3>
    <h3>Six</h3>
    <%= image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1668855070/Kidenglish/Sans_titre_-_2022-11-19T115003.955_e29kqi.png", width:120 %>
  </div>
  <div class="mini">
    <h3>Sept</h3>
    <h3>Seven</h3>
    <%= image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1668855070/Kidenglish/Sans_titre_-_2022-11-19T114909.910_b2vzip.png", width:120 %>
  </div>
  <div class="mini">
    <h3>Huit</h3>
    <h3>Eight</h3>
    <%= image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1668855071/Kidenglish/Sans_titre_-_2022-11-19T114719.571_mj7ag5.png", width:120 %>
  </div>
  <div class="mini">
    <h3>Neuf</h3>
    <h3>Nine</h3>
    <%= image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1668855070/Kidenglish/Sans_titre_-_2022-11-19T114736.032_j5ch0b.png", width:120 %>
  </div>
  <div class="mini">
    <h3>Zero</h3>
    <h3>Zero</h3>
    <%= image_tag"https://res.cloudinary.com/dhxefoe7j/image/upload/v1668855162/Kidenglish/Sans_titre_-_2022-11-19T115233.538_zbruqp.png", width:120 %>
  </div>
</div>

<%= image_tag'https://res.cloudinary.com/dhxefoe7j/image/upload/v1668867412/Kidenglish/Sans_titre_-_2022-11-19T114302.358_d2vqqh.png' %>

app/views/pages/school.html.erb
<%= link_to 'back', dashboard_path %>

app/views/pages/sports.html.erb
<%= link_to 'back', dashboard_path %>

app/views/pages/vegetables.html.erb
<%= link_to 'back', dashboard_path %>